### ISSUE TITLE
In StateDB.ProcessTxs merge calculation of `s.accumulatedFees` and `collectedFees`

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#266]
This is a low priority optimization.

Currently in ProcessTxs the same amount for coordinator fee is calculated twice, once in s.accumulatedFees (indexed by idx), another for collectedFees (indexed by TokenID).  This could be reduced by only calculating the amount once in s.accumulatedFee, and before returning creating the collectedFees map like this:
```go
collectedFees := make(map[common.TokenID]*big.Int)
coordIdxsMap := s.getTokenIDsFromIdxs(coordIdxs) // update getTokenIDsFromIdxs to return map[common.Idx]common.TokenID
for idx, amount := range s.accumulatedFees {
    collectedFees[coordIdxsMap[idx]] = amonut
}
```

**Comment by ed255** [comment]
Related to https://github.com/hermeznetwork/hermez-node/issues/308
There are several optimizations that can be done in the txprocessor regarding the number of kvdb queries that are performed.

Having benchmarks of the entire system will help determine how important it is to apply these optimizations to the tx processor https://github.com/hermeznetwork/hermez-node/issues/283

**Comment by tclemos** [comment]
Well, after a lot of transactions, analysis on tx data, and hermez-node code, it was possible to identify the transactions are not being sorted by `profitability`, but only by `nonce`. 

In order to achieve a sorting order by `profitability` without breaking the nonce sequence, we should do the sorting in the following order: `absolute fee` descending, `idx` ascending, `nonce` ascending

For example, let's consider this txs data as the source of transactions to be forged:

|idx|nonce|absolute fee|
|---|---|---|
|1|1|1|
|1|2|2|
|1|3|3|
|2|1|3|
|2|2|2|
|2|3|1|
|3|2|3|
|3|3|3|
|3|4|3|
|4|2|2|
|4|3|2|
|4|4|2|

the current implementation is resulting in this order of transactions, which is clearly sorting by `nonce`:

|idx|nonce|absolute fee|
|---|---|---|
|2|1|3|
|1|1|1|
|2|2|2|
|3|2|3|
|1|2|2|
|4|2|2|
|3|3|3|
|1|3|3|
|4|3|2|
|2|3|1|
|4|4|2|
|3|4|3|

but the expected result would be, sorting by highest fee and then by idx and nonce:

|idx|nonce|absolute fee|
|---|---|---|
|3|2|3|
|3|3|3|
|3|4|3|
|2|1|3|
|1|3|3|
|4|2|2|
|4|3|2|
|4|4|2|
|2|2|2|
|1|2|2|
|2|3|1|
|1|1|1|

The sorting operation is being handled in these lines: 

- https://github.com/hermeznetwork/hermez-node/blob/f56563897c7570d9bf532a744fbf5a66d10129c2/txselector/txselector.go#L1029

- https://github.com/hermeznetwork/hermez-node/blob/f56563897c7570d9bf532a744fbf5a66d10129c2/txselector/txselector.go#L1029

and as we can see, the second sort operation is the one causing the slice to be sorted only by nonce, overriding the first sort.

in order to fix the sorting operation, we must replace this: 

```go
        // Sort non atomic txs by absolute fee with SliceStable, so that txs with same
	// AbsoluteFee are not rearranged and nonce order is kept in such case
	sort.SliceStable(nonAtomicTxs, func(i, j int) bool {
		return nonAtomicTxs[i].AbsoluteFee > nonAtomicTxs[j].AbsoluteFee
	})

	// sort non atomic txs by Nonce. This can be done in many different ways, what
	// is needed is to output the l2Txs where the Nonce of l2Txs for each
	// Account is sorted, but the l2Txs can not be grouped by sender Account
	// neither by Fee. This is because later on the Nonces will need to be
	// sequential for the zkproof generation.
	sort.Slice(nonAtomicTxs, func(i, j int) bool {
		return nonAtomicTxs[i].Nonce < nonAtomicTxs[j].Nonce
	})
```

by this: 

```go
        sort.Slice(nonAtomicTxs, func(i, j int) bool {
		if nonAtomicTxs[i].AbsoluteFee != nonAtomicTxs[j].AbsoluteFee {
			return nonAtomicTxs[i].AbsoluteFee > nonAtomicTxs[j].AbsoluteFee
		} else if nonAtomicTxs[i].Idx != nonAtomicTxs[j].Idx {
			return nonAtomicTxs[i].Idx > nonAtomicTxs[j].Idx
		} else {
			return nonAtomicTxs[i].Nonce < nonAtomicTxs[j].Nonce
		}
	})                
```


@jeffprestes and @arnaubennassar, before I start changing the code in order to fix the tx order by profitability, could you please double-check my rationale and tell me if I am missing something? 

Thanks in advance.

**Comment by jeffprestes** [comment]
We cannot change the user's nonce order. This is very important to keep the circuit and to avoid frauds. 
What the function needs to check the most profitable fee among first nonce non forged of the users and then order the transaction by them.  
So the example correct order would be:
|idx|nonce|absolute fee|
|---|---|---|
|2|1|3|
|3|2|3|
|3|3|3|
|3|4|3|
|2|2|2|
|4|2|2|
|4|3|2|
|4|4|2|
|2|3|1|
|1|1|1|
|1|2|2|
|1|3|3|

**Comment by jeffprestes** [comment]
And this rule is not applied in Hermez Protocol. This is the same behaviour of Ethereum transaction pool. In case of further questions I would recommend to check GETH's code and Ethereum protocol documentation.

**Comment by tclemos** [comment]
@jeffprestes I agree and you are right, but in order to achieve this, the algorithm would have to deal with also other scenarios, for example, a transaction that can't be processed yet due to not having enough balance, or check if a transaction has an implicit dependency with other transaction in order to enable it. Me and @arnaubennassar discussed this specific point and in order to keep it as simple as possible but still sorting things by profitability, the proposed solution relies on the reprocessing logic in order to execute the `nonces` in the correct order.

Using the expected result from my example, I'll try to illustrate the reprocessing attempts in order to process all the transactions in the correct order considering the proposed sorting solution, it is also important to mention that all these transactions will be forged in the same batch.

|idx | nonce | absolute fee | 1º attempt | 2º attempt | 3º attempt |
| -- | -- | -- | -- | -- | -- | 
| 3 | 2 | 3 | selected | | |
| 3 | 3 | 3 | selected | | |
| 3 | 4 | 3 | selected | | |
| 2 | 1 | 3 | selected | | |
| 1 | 3 | 3 | wrong nonce | wrong nonce | selected |
| 4 | 2 | 2 | selected | | |
| 4 | 3 | 2 | selected | | |
| 4 | 4 | 2 | selected | | |
| 2 | 2 | 2 | selected | | |
| 1 | 2 | 2 | wrong nonce | selected | |
| 2 | 3 | 1 | selected | | |
| 1 | 1 | 1 | selected | | |

**Comment by jeffprestes** [comment]
Great, @tclemos . We respecting nonce order per idx in transaction processing all other enhancements LGTM.
