### ISSUE TITLE
Add the ability to synchronize more than one block per time

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#740]
## Rationale

Now we are sync block by block, the Ethereum client permits we query more them one block per time. This can increase the synchronization time.

## Implementation

Add a range of blocks to fetch if the sum of blocks to fetch is greater than this range.
E.g., The range is 10, and we must sync 23 blocks. We do 2 syncs from 10 blocks and one of 3 blocks.

We must add the `FromBlock` and the `ToBlock`  here
https://github.com/hermeznetwork/hermez-node/blob/381997f3e8394d2f021aa4387e2ba016ded2c75e/eth/rollup.go#L784-L785

**Comment by OBrezhniev** [comment]
Hi @Pantani!
I'm working on it as a part of synchronization improvement I'm doing in [feature/fastsync-concurrent-block-fetching](https://github.com/hermeznetwork/hermez-node/tree/feature/fastsync-concurrent-block-fetching).
The block you are referring to is actually for fetching block events, not blocks (block headers to be precise) themselves.

Right now the whole process of synchronization is very serial: first fetch block headers for the next block, then fetch block events for this block, and do processing after and in-between. Just changing the range here won't work, because the function logic expects here events only for one specific block and will break on range query.

What I'm doing is decoupling of fetching and processing as a first step (you can see WIP in the branch), then move fetching blocks and events outside of the sync loop to a separate loop, fetch events in large batches, fetch blocks in concurrent requests and process them on the event of availability of both next block headers and it's events.

**Comment by tclemos** [comment]
> We are reprioritizing this issue in order to improve the synchronizer performance and maintenance.

## Targets

- Move synchronizer to a separated binary
- Move from a multiple database to a single database solution
- Synchronize L1 data based on events instead block by block
- Synchronize only blocks with Hermez smart contract events
- Process things concurrently and in parallel when possible
- Have two different synchronization strategies: one for old data and another for fresh data in the blockchain
- Allow state data to be visualized/debugged in the database

## Current implementation

Today the node implementation depends on two different databases, it uses `PostgreSQL` and `Peeble`(https://github.com/iden3/go-merkletree/tree/master/db/pebble)

Internally the node has 4 database concepts:

- History: Stores information like `blocks`, `batches`, `tokens` and `tx` synchronized from L1
- L2: Stores information like `account creation authorization` and `tx pool`
- Merkle Tree: Stores information like tree leaves, indexes, data
- State: Stores information the merkle tree state in a certain point in time like current, last and by batch number.

The `History` and `L2` dbs are using `Postgres` to store its data, while `Merkle Tree` and `State` are using `Peeble`.

### Merkle Tree

@OBrezhniev created a fork from `Merkle Tree` repository providing a Merkle Tree `Postgres` storage driver, here is it: https://github.com/iden3/go-merkletree-sql

We are going to use this package to migrate the `Merkle Tree` from `Peeble` to `Postgres`. To keep things simples, we will use the same write configuration as the databases `History` and `L2` to connect to Postgres.

We also need to create two new tables:

```sql
-- +migrate Up
CREATE TABLE mt_nodes (
    mt_id BIGINT,
    key BYTEA,
    type SMALLINT NOT NULL,
    child_l BYTEA,
    child_r BYTEA,
    entry BYTEA,
    created_at BIGINT,
    deleted_at BIGINT,
    PRIMARY KEY(mt_id, key)
);

CREATE TABLE mt_roots (
    mt_id BIGINT PRIMARY KEY,
    key BYTEA,
    created_at BIGINT,
    deleted_at BIGINT
);


-- +migrate Down
DROP TABLE mt_nodes;
DROP TABLE mt_roots;
```

And we finally need to replace instantiation of the Merkle Tree to receive a `Postgres` storage instead of a `Peeble` storage, here is it: https://github.com/hermeznetwork/hermez-node/blob/develop/db/statedb/statedb.go#L143

### State

The current implementation of the `State` is a bit trick, inside of this abstraction we have things related to the synchronizer but also things related to the coordinator, lets try to separate things here to make it clear.

There are 3 different state concepts:

- Current: The current state of the Merkle Tree synchronized from the L1
- Last: It is created from the `Current` state and is changed by the `Coordinator` when forging a new `Batch`
- BatchNum: The state of the `Merkle Tree` for each `Batch` already forged or being forged by the `Coordinator`
