### ISSUE TITLE
Explore more service providers for `priceupdater`

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#922]
## Rationale

Knowing the value in fiat of the different supported tokens it's critical, and relying just on two providers is dangerous

**Comment by krlosMata** [comment]
# Proposal
Get prices for tokens based on chainlink aggregators smart contracts

## Rationale
Current approach relies on two external services to get token prices.
This new approach relies on chainlink price feeds provided by its aggregators. Chainlink prices are updated on its aggregators smart contracts. Behind the scenes, those prices are taken from several third party services and includes mechanisms in order to to manipulate the price and ensures that the price is correct.
As an example, ethereum price is updated in the chainlink smart contract and it get prices from 31 service providers: https://data.chain.link/ethereum/mainnet/crypto-usd/eth-usd
This approach also allow to hermez-node to rely only on ethereum client, since only smart contract aggregators are needed in order to retrieve prices.
Chainlink provides price feeds in several well-known platforms which get the prices inside smart contracts and thus chainlink provide better reliability than a single external service.

## Limitations
Not all tokens are available through chainlink aggregators.
In such a case, my suggestion is to get prices from uniswap pools, which also provides accurate prices.
Futhermore, prices are very tight to exchanges prices since arbitrage opportunities make the uniswap prices very reliable and hermez-node will still depend only on ethereum client.

## Example
Yoy can find here an example of how to retrieve prices from chainlink smart contract aggregators: https://github.com/krlosMata/prices-chainlink

**Comment by krlosMata** [comment]
## Example
You can find here an example of how to retrieve prices from uniswap pair smart contracts:
https://github.com/krlosMata/prices-uniswap

**Comment by jeffprestes** [comment]
@marioidival already implemented the token price update getting data from Uniswap. If another provided please open a new issue.
