### ISSUE TITLE
Move abi files to hermez-node and update bash script eth/contracts/update.sh to work properly

### ISSUE THREAD

**Issue by marioidival** [hermeznetwork/hermez-node#943]
## Rationale

Update shell script that generates Go Proxy artifacts to interact with Hermez Smart Contracts to make easier and faster when a change would be made at the Smart Contracts. 

## Implementation

 - Update the contracts ABI in hermez-node repo
 - Generates the Go Proxy Smart Contract artifacts using GETH abigen tool

**Comment by ARR552** [comment]
Related - #779 and #119

**Comment by ARR552** [comment]
I think abi files shouldn't be stored in the hermez-node repository. This info is in contracts repo.

**Comment by jeffprestes** [comment]
I am afraid to disagree @ARR552 . Please let me explain why.
First let's clarify a point. It's recommended that a project that compile his code into a binary has all dependencies in their code base to be able to compile anytime, regardless of third-party availability.
In this particular case, this ABI content is part of hermez-node source because it will become our hermez-node go code after using abigen. Without it we could not generate hermez-node go source. Hence, it is part of hermez-node source code. It is a dependency.
Besides this, the contract project could have independent lifecycle and hermez-node maintainers could decide when it is the best moment to update the interfaces to the contract.
